twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    # PERMET DE DEFINIR DES VARIABLES GLOBALES
    # globals:
    #     offset : 6
