<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.UIav4EF' shared service.

return $this->privates['.service_locator.UIav4EF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'repo' => ['privates', 'App\\Repository\\EspecesRepository', 'getEspecesRepositoryService.php', true],
], [
    'repo' => 'App\\Repository\\EspecesRepository',
]);
