<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.L_d7d8W' shared service.

return $this->privates['.service_locator.L_d7d8W'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'especes_repo' => ['privates', 'App\\Repository\\EspecesRepository', 'getEspecesRepositoryService.php', true],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'sortie' => ['privates', '.errored..service_locator.L_d7d8W.App\\Entity\\Sortie', NULL, 'Cannot autowire service ".service_locator.L_d7d8W": it references class "App\\Entity\\Sortie" but no such service exists.'],
    'spot_repo' => ['privates', 'App\\Repository\\SpotRepository', 'getSpotRepositoryService.php', true],
], [
    'especes_repo' => 'App\\Repository\\EspecesRepository',
    'manager' => '?',
    'sortie' => 'App\\Entity\\Sortie',
    'spot_repo' => 'App\\Repository\\SpotRepository',
]);
