<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.b0oHW00' shared service.

return $this->privates['.service_locator.b0oHW00'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'sortie' => ['privates', '.errored..service_locator.b0oHW00.App\\Entity\\Sortie', NULL, 'Cannot autowire service ".service_locator.b0oHW00": it references class "App\\Entity\\Sortie" but no such service exists.'],
], [
    'manager' => '?',
    'sortie' => 'App\\Entity\\Sortie',
]);
