<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._Sr0diX' shared service.

return $this->privates['.service_locator._Sr0diX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'site' => ['privates', '.errored..service_locator._Sr0diX.App\\Entity\\Site', NULL, 'Cannot autowire service ".service_locator._Sr0diX": it references class "App\\Entity\\Site" but no such service exists.'],
], [
    'manager' => '?',
    'site' => 'App\\Entity\\Site',
]);
