<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.HiJXSh2' shared service.

return $this->privates['.service_locator.HiJXSh2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
    'site_repo' => ['privates', 'App\\Repository\\SiteRepository', 'getSiteRepositoryService.php', true],
    'spot_repo' => ['privates', 'App\\Repository\\SpotRepository', 'getSpotRepositoryService.php', true],
], [
    'manager' => '?',
    'site_repo' => 'App\\Repository\\SiteRepository',
    'spot_repo' => 'App\\Repository\\SpotRepository',
]);
