<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.cMKxvhb' shared service.

return $this->privates['.service_locator.cMKxvhb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'site' => ['privates', '.errored..service_locator.cMKxvhb.App\\Entity\\Site', NULL, 'Cannot autowire service ".service_locator.cMKxvhb": it references class "App\\Entity\\Site" but no such service exists.'],
], [
    'site' => 'App\\Entity\\Site',
]);
