<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8Wy5lvr' shared service.

return $this->privates['.service_locator.8Wy5lvr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'espece' => ['privates', '.errored..service_locator.8Wy5lvr.App\\Entity\\Especes', NULL, 'Cannot autowire service ".service_locator.8Wy5lvr": it references class "App\\Entity\\Especes" but no such service exists.'],
    'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
], [
    'espece' => 'App\\Entity\\Especes',
    'manager' => '?',
]);
