<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNWTfTzM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNWTfTzM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNWTfTzM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNWTfTzM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerNWTfTzM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'NWTfTzM',
    'container.build_id' => '43a3c58c',
    'container.build_time' => 1608800115,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNWTfTzM');
